// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD14uy1FBa9LURdx8EkSM25EPg7xEcdJb4',
    appId: '1:252805092105:web:fe025d48efa981c572b9d8',
    messagingSenderId: '252805092105',
    projectId: 'magang-godseo',
    authDomain: 'magang-godseo.firebaseapp.com',
    storageBucket: 'magang-godseo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr85cp-6T1mcBASEgV0g7o0e0VbI5dxVU',
    appId: '1:252805092105:android:2faafff05009329972b9d8',
    messagingSenderId: '252805092105',
    projectId: 'magang-godseo',
    storageBucket: 'magang-godseo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAitck8Q9wGhxknFccdisgzSpxl72gQD1c',
    appId: '1:252805092105:ios:5441b93c124f4daa72b9d8',
    messagingSenderId: '252805092105',
    projectId: 'magang-godseo',
    storageBucket: 'magang-godseo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAitck8Q9wGhxknFccdisgzSpxl72gQD1c',
    appId: '1:252805092105:ios:e083a00b6c62e09772b9d8',
    messagingSenderId: '252805092105',
    projectId: 'magang-godseo',
    storageBucket: 'magang-godseo.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
